blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/MrThiemann/lovelace-ios/discussions
    about: Please ask and answer questions here.
  - name: 💬 Chat
    url: https://discord.gg/zhdmdhU
    about: Our Discord-Community Server
  - name: 🚀 Feature Request
    url: https://github.com/MrThiemann/lovelace-ios/discussions/new?category=feature-requests
  - name: SmartHomeYourSelf Homepage
    url: https://smarthomeyourself.de
    about: SmartHomeYourSelf Community Homepage - with Scripts and Tutorials for your HomeAssistant, and many more...
